# PA2 - Numpy

In [5]:
import numpy as np

#### Problem 1 - Normalization Problem

In [95]:
#Create a random 5x5 ndarray
X = np.random.random((5,5))

#Use the formula for normalization
Z = (X - X.mean()) / X.std()

#Save the result to a file named 'X_normalized.npy'
np.save('X_normalized.npy', Z)

In [184]:
#Load and display the saved ndarray from the file
array = np.load('X_normalized.npy')
print(array)

[[ 0.11674555  1.27114896 -0.77778153  0.01817089 -1.08760372]
 [ 0.85278186  1.08352637  0.98368374  1.03672392 -1.42856932]
 [-0.0596307  -1.71853473  0.93152963  1.10755926 -0.42389101]
 [-0.72583447  1.33554247  0.43705157 -1.47261055 -1.37363689]
 [-1.08961115  0.71414721  1.26582131 -0.58074155 -0.41598713]]


#### Problem 2 - Divisible by 3 Problem

In [192]:
#Create a 10x10 ndarray with squares of the first 100 positive integers
S = np.arange(1, 101).reshape(10, 10) ** 2 
print(S)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [218]:
#Determine elements divisible by 3
div_by_3 = S[S % 3 == 0]

#Save the result to a file named 'div_by_3.npy'
np.save('div_by_3.npy', div_by_3)

In [212]:
#Load display and the saved ndarray from the file
array = np.load('div_by_3.npy')
print(array)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
